version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      # Mount the entire project directory for hot-reloading
      - .:/app
      # Persist the SQLite database outside the container
      - db_data:/app/data
    environment:
      # Use the secret key from auth.py
      - SECRET_KEY=your-secret-key-change-in-production

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      # Mount the frontend source code for hot-reloading
      - ./frontend:/app
      # Use an anonymous volume for node_modules to avoid host conflicts
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data:
